export enum tagTypes {
  profile = "profile",
  users = "users",
  vendorDocument = "vendorDocument",
  packages = "packages",
  addons = "addons",
  bookings = "bookings",
  vendor = "vendor",
  cleaners = "cleaners",
  transactions = "transactions",
  services = "services",
  admin = "admin",
  categories = "categories",
  pages = "pages",
  blogs = "blogs",
  documents = "documents",
  inventory = "inventory",
}

export const tagTypesList = [
  tagTypes.profile, 
  tagTypes.users, 
  tagTypes.vendorDocument, 
  tagTypes.packages, 
  tagTypes.addons,
  tagTypes.bookings,
  tagTypes.vendor,
  tagTypes.cleaners,
  tagTypes.transactions,
  tagTypes.services,
  tagTypes.admin,
  tagTypes.categories,
  tagTypes.pages,
  tagTypes.blogs,
  tagTypes.documents,
  tagTypes.inventory,
];
